[tool.poetry]
name = "replitdb"
version = "0.1.0"
description = "Interface with repl.it database"
authors = ["Scoder12 <34356756+Scoder12@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
darglint = "^1.5.2"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.1.4"
black = "^19.10b0"
flake8-black = "^0.2.1"
flake8-import-order = "^0.18.1"
flake8-annotations = "^2.3.0"
flake8-docstrings = "^1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
